name: Publish ui-vite To Npm
on:
  push:
    branches: [publish-ui-vite]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "publish npm"
    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: 7.11.0
      - name: Install modules
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: npm run build
      - name: "Publish to the npm registry"
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        with:
          default_branch: "publish"
